### Importing Libraries


In [2]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [3]:
# Importing Dataset & Extracting Features
dis = pd.read_csv('../data/dateset1/Training.csv')
X = dis.iloc[:, :-1].values
y = dis.iloc[:, -1].values

# Data Splitting & Preprocessing 
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)


In [ ]:
# KNN -> Model # 2
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

1.0

[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
