### Importing Libraries


In [2]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [3]:
# Importing Dataset & Extracting Features
dis = pd.read_csv('../data/dateset1/Training.csv')
X = dis.iloc[:, :-1].values
y = dis.iloc[:, -1].values

# Data Splitting & Preprocessing 
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)


In [4]:
# SVC -> Model # 1
from sklearn.svm import SVC
clf = SVC(C=10, kernel='poly', degree=3)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

1.0

[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [5]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train,cv=10)
scores.mean()

1.0

In [34]:
# SVC -> Model # 1
''' 
# clf = SVC(C=10, kernel='poly', degree=3)
from sklearn.svm import SVC
param_grid = {'C':[0.001, 0.01, 0.1, 1, 10, 100],
               'gamma' : [0.001, 0.01, 0.1, 1, 10, 100]}

grid_search = GridSearchCV(SVC(), param_grid, cv=5)
grid_search.fit(X_train, y_train)
y_pred = grid_search.predict(X_test)



# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
'''

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'gamma': [0.001, 0.01, 0.1, 1, 10, 100]})

In [43]:
# KNN -> Model # 2
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

1.0

[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [47]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train,cv=10)
scores.mean()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Logistic Regression -> Model # 3
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter=10000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

1.0

[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [10]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train,cv=10)
scores.mean()

1.0

In [95]:
# DT -> Model # 4
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy', random_state = 0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

1.0

[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [96]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train,cv=20)
scores.mean()

0.9988372093023257

In [99]:
# Random Forests -> Model # 4
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, max_depth=10, max_leaf_nodes=5)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)


# Evaluation
'''  
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
'''

'  \nfrom sklearn.metrics import accuracy_score\nprint(accuracy_score(y_test, y_pred))\nprint()\nfrom sklearn.metrics import confusion_matrix\nprint(confusion_matrix(y_test, y_pred))\n'

In [109]:


# # hyper paramter tuning
# clf = RandomForestClassifier(n_estimators=100, max_depth=10, max_leaf_nodes=5)
param_grid = {'n_estimators':list(range(2,10)),
               'max_depth' : list(range(2,10)),
               'max_leaf_nodes' : list(range(2,10))
               }

grid_search = GridSearchCV(RandomForestClassifier(), param_grid, cv=5)
grid_search.fit(X_train, y_train)
grid_search.predict(X_test)



# Evaluation
''' 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
'''






# function
''' 
tst = []

for k in range(1,20):
    knn_model = RandomForestClassifier(n_estimators=100, max_depth=10, max_leaf_nodes=6)
    knn_model.fit(X_train,y_train) 
   
    y_pred_test = knn_model.predict(X_test)
    tst.append(accuracy_score(y_test,y_pred_test))
tst
'''

' \ntst = []\n\nfor k in range(1,20):\n    knn_model = RandomForestClassifier(n_estimators=100, max_depth=10, max_leaf_nodes=6)\n    knn_model.fit(X_train,y_train) \n   \n    y_pred_test = knn_model.predict(X_test)\n    tst.append(accuracy_score(y_test,y_pred_test))\ntst\n'

In [121]:
pd.DataFrame(grid_search.cv_results_)[['mean_test_score', 'std_test_score', 'params']]



mean_test_score  std_test_score  \
0           0.074623        0.002851   
1           0.089717        0.011114   
2           0.113243        0.011382   
3           0.120790        0.000567   
4           0.141696        0.010125   
..               ...             ...   
507         0.624568        0.033617   
508         0.666647        0.052821   
509         0.694233        0.057349   
510         0.729081        0.043369   
511         0.800821        0.043639   

                                                params  
0    {'max_depth': 2, 'max_leaf_nodes': 2, 'n_estim...  
1    {'max_depth': 2, 'max_leaf_nodes': 2, 'n_estim...  
2    {'max_depth': 2, 'max_leaf_nodes': 2, 'n_estim...  
3    {'max_depth': 2, 'max_leaf_nodes': 2, 'n_estim...  
4    {'max_depth': 2, 'max_leaf_nodes': 2, 'n_estim...  
..                                                 ...  
507  {'max_depth': 9, 'max_leaf_nodes': 9, 'n_estim...  
508  {'max_depth': 9, 'max_leaf_nodes': 9, 'n_estim...  
509  {'max_depth': 9, 'max_leaf_nodes': 9, 'n_estim...  
510  {'max_depth': 9, 'max_leaf_nodes': 9, 'n_estim...  
511  {'max_depth': 9, 'max_leaf_nodes': 9, 'n_estim...  

[512 rows x 3 columns]

In [127]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train,cv=10, scoring="accuracy")
# scores = cross_val_predict(clf, X_train, y_train,cv=10)
scores

array([0.95072464, 0.88405797, 0.86956522, 0.96811594, 0.87790698,
       0.90988372, 0.92151163, 0.92151163, 0.97383721, 0.9505814 ])

In [15]:
# Naive Bayes -> Model # 5
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))
print()
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

1.0

[[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]


In [16]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train,cv=10)
scores.mean()

1.0